#ifndef LIB_HYPERFOCALTREATMENT_GLOBAL_H
#define LIB_HYPERFOCALTREATMENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIB_HYPERFOCALTREATMENT_LIBRARY)
#  define LIB_HYPERFOCALTREATMENT_EXPORT Q_DECL_EXPORT
#else
#  define LIB_HYPERFOCALTREATMENT_EXPORT Q_DECL_IMPORT
#endif

#endif // LIB_HYPERFOCALTREATMENT_GLOBAL_H
